---
- name: Ansible playbook for installing the flutter
  hosts: localhost
  gather_facts: true
  vars:
    is_WSL: "{{ ansible_kernel.find('WSL') }}"
    DISTRO_VERSION: 3.4
    YOCTO_BRANCH: honister
    MACHINE: raspberrypi3
  tasks:
    - name: Check yocto resources
      ansible.builtin.stat:
        path: sources
      register: p
    - name: Init repo with Google repo tool
      when: not p.stat.exists
      command: repo init -u https://github.com/Gmatarrubia/yocto-rpi-manifests.git -m rpi32.xml -b "{{ YOCTO_BRANCH }}"
    - name: Repo sync force
      command: repo sync --force-sync --no-clone-bundle -j "{{ansible_processor_vcpus}}"
    - name: Checking out specifict branch
      command: git checkout "{{ YOCTO_BRANCH }}-{{DISTRO_VERSION}}"
      args:
        chdir: sources/poky

