#!/bin/bash

# This script is the entry point for the docker container.
# It will add the host machine's user to the dockern and then execute userentry.sh

if (grep -s -q "^$USER:" /etc/passwd); then
    echo "found $USER in docker container"
else
    echo "adding host machine user $USER ($UID) to docker container"
    grep -s -q ":$GID:" /etc/group || groupadd -g "$GID" "$GROUP"
    useradd -d /yocto -u "$UID" -g "$GID" "$USER"
    echo "$USER:$USER" | chpasswd
fi
# Allow sudo without password
echo "$USER ALL=(root) NOPASSWD: /usr/bin/ansible-playbook *" >> /etc/sudoers

export PATH=/yocto:${PATH}

if [ -z "$(which python3)" ]
then
    sudo --user="${USER}" /yocto/installDevEnv.sh
fi

# Check if it's needed to init Yocto devEnv
if [ ! -d /yocto/sources ]
then
    ln -s /usr/bin/python3 /usr/bin/python
    sudo --user="${USER}" kas checkout rpi-flutter.yml
    chown -R $USER:$USER /yocto/sources
    chmod -R 755 /yocto/sources
fi

# preserve sanctioned env vars for all users within the docker instance
if [ $# -eq 0 ]
then
    exec sudo --user="${USER}" /bin/bash
else
    exec sudo --user="${USER}" "$@"
fi
